[0;33m--- esp-idf-monitor 1.2.1 on /dev/ttyUSB0 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[0;33m0x400d89a2: send_web_page at /home/comfi/esp/low-power-dashboard/main/wifi_ap.c:220 (discriminator 1)
[0m
[0;33m0x4000c46c: memset in ROM
[0m
[0;33m0x4000c477: memset in ROM
[0m
[0;33m0x400d899f: send_web_page at /home/comfi/esp/low-power-dashboard/main/wifi_ap.c:220 (discriminator 1)
[0m
[0;33m0x400d8a09: get_req_handler at /home/comfi/esp/low-power-dashboard/main/wifi_ap.c:233
[0m
[0;33m0x40102faf: httpd_uri at /home/comfi/esp/esp-idf/components/esp_http_server/src/httpd_uri.c:329
[0m
[0;33m0x40103829: httpd_parse_req at /home/comfi/esp/esp-idf/components/esp_http_server/src/httpd_parse.c:667 (discriminator 15)
[0m
[0;33m0x401038c8: httpd_req_new at /home/comfi/esp/esp-idf/components/esp_http_server/src/httpd_parse.c:795
[0m
[0;33m0x40102718: httpd_sess_process at /home/comfi/esp/esp-idf/components/esp_http_server/src/httpd_sess.c:426 (discriminator 15)
[0m
[0;33m0x40101910: httpd_process_session at /home/comfi/esp/esp-idf/components/esp_http_server/src/httpd_main.c:255 (discriminator 15)
[0m
[0;33m0x40174b27: httpd_sess_enum at /home/comfi/esp/esp-idf/components/esp_http_server/src/httpd_sess.c:50 (discriminator 1)
[0m
[0;33m0x401020da: httpd_server at /home/comfi/esp/esp-idf/components/esp_http_server/src/httpd_main.c:305
[0m
[0;33m0x40102146: httpd_thread at /home/comfi/esp/esp-idf/components/esp_http_server/src/httpd_main.c:327 (discriminator 15)
[0m
[0;33m0x4008da4d: vPortTaskWrapper at /home/comfi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:162
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0mException in thread Thread-2 (_run_outer):
Traceback (most recent call last):
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 76, in run
    data = self.serial.read(self.serial.in_waiting or 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 83, in run
    self.close_serial()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 105, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 119, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 100, in run
    self.close_serial()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 105, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 119, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error
[0m
